namespace Prototype.Enum;

public enum ActionTypeEnum
{
    Create,
    CreateUser,
    Read,
    Update,
    Get,
    Delete,
    Login,
    Logout,
    AssignPermission,
    RevokePermission,
    ChangePassword,
    ChangeUsername,
    FailedLogin,
    Export,
    Import,
    Approve,
    Reject,
    Enable,
    Disable,
    ForgotUsername,
    ForgotPassword,
    ConnectionAttempt,
    ConnectionSuccess,
    ConnectionFailure,
    ConnectionChanged,
    ApplicationAdded,
    ApplicationRemoved,
    StatusChanged,
    HealthCheck,
    ResponseTimeMeasured,
    ErrorLogged,
    Other,
    ApplicationUpdated
}